### ISSUE TITLE
100% height layout

### ISSUE THREAD

**Issue by jlukic** [percolatestudio/atmosphere#292]
It looks like the site wasnt built with sticky footers, so on short pages, the content doesn't fill the entire screen correctly.

For example [here](https://atmospherejs.com/lumatijev)

A simple solution would be 

``` css
.applicationLayout > .content {
  display: flex;
  min-height: 100vh;
  flex-direction: column;
}
.applicationLayout > .content > .page {
  flex: 1;
}
```

You can see this technique used [here](http://beta.semantic-ui.com/globals/reset.html)
